### ISSUE TITLE
Support asynchronous image analysis task creation

### ISSUE THREAD

**Issue by djhi** [ariadnext/nodejs-IDCHECKIO#1]
This implies:
- adding a parameter for asynchronous analysis on `analyseImage` or adding a dedicated function which should return the task's identifier
- adding a function to check for task completion
- adding a function to retrieve the analysis result

**Comment by julienandre** [comment]
Hello djhi,
I will update the library asap.
Did you get some credits to test the ID check service throught the API ?

**Comment by djhi** [comment]
Yes, I'm currently working with it for a customer. We implemented async on our side for now.

**Comment by julienandre** [comment]
Hello, 
The new version 2.2.0 add the asynchronous parameters in functions as well as the "analysisResult" & "analysisStatus".
This client library should be now equivalent to the API.
-> Do not hesitate to contact me for any questions, requests or problems into this integration.
Regards, 
JA
